//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leanwork.Rh.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leanwork.Rh.Domain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório.
        /// </summary>
        internal static string MessageBlankField {
            get {
                return ResourceManager.GetString("MessageBlankField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter entre {1} e {2} caracteres..
        /// </summary>
        internal static string MessageMinimumFieldMaximumCharacters {
            get {
                return ResourceManager.GetString("MessageMinimumFieldMaximumCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não pode ser nulo..
        /// </summary>
        internal static string NullFieldMessage {
            get {
                return ResourceManager.GetString("NullFieldMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter {1} caracteres..
        /// </summary>
        internal static string MessageMaximumFieldCharacters {
            get {
                return ResourceManager.GetString("MessageMaximumFieldCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser vinculado na entidade {1}.
        /// </summary>
        internal static string MessageFieldNotLinked {
            get {
                return ResourceManager.GetString("MessageFieldNotLinked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo {0} esta no formato inválido.
        /// </summary>
        internal static string MessageFieldCPFOrCNPJInvalid {
            get {
                return ResourceManager.GetString("MessageFieldCPFOrCNPJInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo {0} esta no formato inválido, {1} não pode ser menor de idade.
        /// </summary>
        internal static string MessageFieldDateOfBirth {
            get {
                return ResourceManager.GetString("MessageFieldDateOfBirth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O {0} esta no formato inválido.
        /// </summary>
        internal static string MessageFieldStateInvalid {
            get {
                return ResourceManager.GetString("MessageFieldStateInvalid", resourceCulture);
            }
        }
    }
}
